unique_ids:
  assets:
    standard-page.html: RRGHEQFHYJQ4JR3P67DRQE7XN5SW2C6S
    theme.css: YS5ACMUQS56CFNLYOWT5TEJBUYAOWWVF
  forms:
    Form1: 47KBGHXRZWTTZ3Q3EY4S4BYG6PQFPK3A
  modules: {}
  scripts: {}
  server_modules: {}
